global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "traefik"
    metrics_path: /metrics
    static_configs:
      - targets: ["172.31.48.235:8080"]

  - job_name: "node"
    static_configs:
      - targets: ["172.31.48.235:9100"]

  - job_name: "redis"
    static_configs:
      - targets: ["172.31.48.235:9121"]

  - job_name: "postgres"
    static_configs:
      - targets: ["172.31.48.235:9187"]
