global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "traefik"
    metrics_path: /metrics
    static_configs:
      - targets: ["traefik:8080"]

  - job_name: "flask"
    metrics_path: /metrics
    static_configs:
      - targets: ["devops-app:5000"]
